spring.application.name=oficioya

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.edu.eci.dosw.oficioya=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n